name: 'firebase_demo'
version: 0.0.1
description: Simple demo of Dart and Firebase
author: Jana MoudraÌ <jana.moudra@gmail.com>
homepage: https://github.com/Janamou/firebase-demo

environment:
  sdk: '>=1.18.0 <2.0.0'

dependencies:
  firebase: '^3.0.0'

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter
